trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - simplic-taskscheduler/*

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'
    
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'simplic-taskscheduler/**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'

- task: MSBuild@1
  inputs:
    solution: 'simplic-taskscheduler/**/*.sln'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Simplic.TaskScheduler.Test.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: 'simplic-taskscheduler'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'simplic-taskscheduler/Simplic.TaskScheduler**/*.csproj;!simplic-taskscheduler/Simplic.TaskScheduler.Test/Simplic.TaskScheduler.Test.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'

- task: NuGetCommand@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/Simplic.TaskScheduler.*.nupkg;!$(Build.ArtifactStagingDirectory)/Simplic.TaskScheduler.*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'
    allowPackageConflicts: true
