trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - simplic-authorization/src/*
    - simplic-authorization/test/*
    - simplic-authorization/azure-pipelines.yml

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - simplic-authorization/src/*
    - simplic-authorization/test/*
    - simplic-authorization/azure-pipelines.yml

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'
    
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'simplic-authorization/**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'

- task: MSBuild@1
  inputs:
    solution: 'simplic-authorization/**/*.sln'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Simplic.Authorization.Test.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: 'simplic-authorization'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'simplic-authorization/Simplic.Authorization**/*.csproj;!simplic-authorization/Simplic.Authorization.Test/Simplic.Authorization.Test.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'

- task: NuGetCommand@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/Simplic.Authorization.*.nupkg;!$(Build.ArtifactStagingDirectory)/Simplic.Authorization.*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'
    allowPackageConflicts: true
