trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/*
    - test/*
    - azure-pipelines.yml

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'
    
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      simplic-cache\**\Simplic.Cache.Test.dll
      !simplic-cache\**\*TestAdapter.dll
      !simplic-cache\**\obj\**
    searchFolder: 'simplic-cache'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Simplic.Cache**/*.csproj;!Simplic.Cache.Test/Simplic.Cache.Test.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/Simplic.Cache.*.nupkg;!$(Build.ArtifactStagingDirectory)/Simplic.Cache.*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'
    allowPackageConflicts: true