trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - simplic-configurationanalyser/*

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - simplic-configurationanalyser/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'
    
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'simplic-configurationanalyser/**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'

- task: MSBuild@1
  inputs:
    solution: 'simplic-configurationanalyser/**/*.sln'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Simplic.ConfigurationAnalyzer.Test.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: 'simplic-configurationanalyser'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'simplic-configurationanalyser/Simplic.ConfigurationAnalyzer**/*.csproj;!simplic-configurationanalyser/Simplic.ConfigurationAnalyzer.Test/Simplic.ConfigurationAnalyzer.Test.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'

- task: NuGetCommand@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/Simplic.ConfigurationAnalyzer.*.nupkg;!$(Build.ArtifactStagingDirectory)/Simplic.ConfigurationAnalyzer.*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'
    allowPackageConflicts: true
