trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - simplic-template-parser/src/*
    - simplic-template-parser/test/*
    - simplic-template-parser/azure-pipelines.yml

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - simplic-template-parser/src/*
    - simplic-template-parser/test/*
    - simplic-template-parser/azure-pipelines.yml

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'
    
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'simplic-template-parser/**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'

- task: MSBuild@1
  inputs:
    solution: 'simplic-template-parser/**/*.sln'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'simplic-template-parser/Simplic.TemplateParser**/*.csproj;!simplic-template-parser/Simplic.TemplateParser.Test/Simplic.TemplateParser.Test.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'

- task: NuGetCommand@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/TemplateParser.*.nupkg;!$(Build.ArtifactStagingDirectory)/TemplateParser.*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e'
    allowPackageConflicts: true
